name: "Dev Docs"

on: [push, pull_request]

jobs:
  build-docs:
    strategy:
      matrix:
        python-version:
          - '3.9'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Need full history to determine version number.
          fetch-depth: 0
      - name: 'Set up Python ${{ matrix.python-version }}'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # this is needed for building @jbms modified sphinx-immaterial theme from src
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install docs deps
        run: python3 -m pip install -r docs/requirements.txt

      - name: Build documentation
        working-directory: docs
        run: sphinx-build -E -W . _build

      - name: Upload docs as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/_build/**

      - name: Publish to gh-pages
        # Only publish package on push to tag or default branch.
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501 # v3.7.3 (2020-10-20)
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
